### ISSUE TITLE
Deploy to internet

### ISSUE THREAD

**Issue by obliviusm** [vetaluga/proje-t-summarySM-#2]
- Deploy `master` branch to some hosting (i recommend http://surge.sh/)
- Add link to `readme` file
- Deploy new version of the site each time new changes are made to `master`

**Comment by vetaluga** [comment]
I did

**Comment by obliviusm** [comment]
Then make pull request

**Comment by obliviusm** [comment]
@vetaluga please, attach here an instruction that you've used to create github page site.
Also, in future, if you use some article or instruction to solve an issue then please attach this link to the issue. It will be helpful for me and in the future in general

**Comment by obliviusm** [comment]
@vetaluga Also, next time tell what you've done and what do i need to look at. not just `I did`. it's not informative at all :)

**Comment by vetaluga** [comment]
![image](https://cloud.githubusercontent.com/assets/28570154/26049244/f6a6c72a-3962-11e7-80b4-9dde19b762f6.png)

**Comment by vetaluga** [comment]
Im open settings this perository and looks on GitHub Pages select "Source", click "master branch".
![image](https://cloud.githubusercontent.com/assets/28570154/26049533/049f24c0-3964-11e7-9379-6c192db2b3ab.png)

**Comment by vetaluga** [comment]
I did "Deploy to Internet". Create textfile and push ( <- right word?) site to internet. 
http://resumesm.bitballoon.com/

**Comment by obliviusm** [comment]
@vetaluga good enough. please, write few words about another hosting as well

**Comment by vetaluga** [comment]
Another hostings is bad, nothing understand, so much spam. Top sites famuos, because need buy their HOST ("adducation" услугу)

**Comment by obliviusm** [comment]
Good enough
